---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iris
    app.kubernetes.io/release: "1.0.0"
  name: iris
spec:
  ports:
  - name: "iris-http"
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: iris
    app.kubernetes.io/release: "1.0.0"
  type: LoadBalancer