---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
  name: nats
spec:
  ports:
  - name: "4222"
    port: 4222
    targetPort: 4222
  - name: "8222"
    port: 8222
    targetPort: 8222
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nats
  name: nats
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: nats
    spec:
      containers:
      - name: nats
        image: nats-streaming
        ports:
        - containerPort: 4222
        - containerPort: 8222
        resources: {}
      restartPolicy: Always
status: {}


        

