---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-ws-config
  labels:
    app.kubernetes.io/name: nats-ws
    app.kubernetes.io/release: 1.0.0
data:
  NATS_URL: "nats:4222"
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats-ws
  name: nats-ws
spec:
  ports:
  - name: "websocket"
    port: 4223
    targetPort: 4223
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats-ws


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nats-ws
  name: nats-ws
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: nats-ws
    spec:
      containers:
      - name: nats-ws
        image: consensyshellhound/nats-relay:v1.3.0
        ports:
        - containerPort: 4223
        envFrom:
        - configMapRef:
            name: nats-ws-config     
        resources: {}
      restartPolicy: Always
status: {}


        

