---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pythia-config
  labels:
    app.kubernetes.io/name: pythia
    app.kubernetes.io/release: 1.0.0
data:
  JAEGER_AGENT_HOST_PORT: "jaeger-agent:5775"
  CASSANDRA_HOST: "cassandra"
  NATS_URL: "nats://nats:4222"
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pythia
  labels:
    app.kubernetes.io/name: pythia
    app.kubernetes.io/release: "1.0.0"
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: pythia
        app.kubernetes.io/release: "1.0.0"
    spec:
      containers:
      - name: pythia
        image: "consensyshellhound/pythia:v1.5.3"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pythia-config          
      restartPolicy: Always
status: {}