---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fuel-config
  labels:
    app.kubernetes.io/name: fuel
    app.kubernetes.io/release: 1.0.0
data:
  NODE_URI: "http://styx:8545"
  SEED: "unfold bachelor enact fiber later donate uncover once torch figure engine keep"
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fuel
  labels:
    app.kubernetes.io/name: fuel
    app.kubernetes.io/release: "1.0.0"
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: fuel
        app.kubernetes.io/release: "1.0.0"
    spec:
      containers:
      - name: iris
        image: "fuelnet/fuel-server:hellhound"
        imagePullPolicy: Always
        ports:
          - containerPort: 4000
        envFrom:
        - configMapRef:
            name: fuel-config          
      restartPolicy: Always
status: {}