---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: styx
  labels:
    app.kubernetes.io/name: styx
    app.kubernetes.io/release: "1.0.0"
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: styx
        app.kubernetes.io/release: "1.0.0"
    spec:
      containers:
      - name: styx
        image: "consensyshellhound/styx:v1.1.2"
        imagePullPolicy: Always
        ports:
          - containerPort: 7214   
      restartPolicy: Always
status: {}