---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: styx
    app.kubernetes.io/release: "1.0.0"
  name: styx
spec:
  ports:
  - name: "styx-http"
    port: 7214
    targetPort: 7214
  selector:
    app.kubernetes.io/name: styx
    app.kubernetes.io/release: "1.0.0"
  type: LoadBalancer